language: node_js
node_js:
- '9'

install: npm install

addons:
  ssh_known_hosts: 119.29.252.110

before_deploy:
- openssl aes-256-cbc -K $encrypted_56719d5475c2_key -iv $encrypted_56719d5475c2_iv -in deploy_rsa.enc -out deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 deploy_rsa
- ssh-add deploy_rsa

deploy:
  provider: script
  script: bash script/deploy.sh
  skip_cleanup: true
  on:
    branch: master
